name: Linting

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "requirements.txt"
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: pip install black

      - name: Check formatting
        run: python -m black --check --diff .
